transport:
  # fs:
  #   root: tmp/fstest
  #   pollInterval: 2s
  s3:
    bucket: gitpod-genie-test
    region: eu-central-1
    pollInterval: 2s
handler:
  binaries:
    kubectl: /usr/bin/kubectl
  timeouts:
    unary: 10s
    stream: 10m
