packages:
  - name: lib
    type: yarn
    deps:
      - components/content-service-api/typescript:lib
      - components/gitpod-protocol:lib
      - dev/mochaw:lib
    srcs:
      - "src/*.ts"
      - "src/*.js"
      - package.json
      - mocha.opts
    config:
      packaging: library
      dontTest: false
      commands:
        # leeway executes the build and test step in the wrong order, so we need to call a special script that builds before testing
        test: ["yarn", "test:leeway"]
      yarnLock: ${coreYarnLockBase}/../yarn.lock
      tsconfig: tsconfig.json
